### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by RIT-entertainment** [ajsya/scratchstudioinviter#2]
It doesn't work...
Here is my code: https://replit.com/@r-pie/AdequateLividScales#main.py
Here is the error:
`Traceback (most recent call last):
  File "main.py", line 18, in <module>
    message = obj[0]['content']
IndexError: list index out of range`

**Comment by ajsya** [comment]
Hi, when I wrote the program it worked, I can assure you that much. Scratch recently updated their api breaking the module I was using. I since switched to a different module and updated the code. The code should now work again. If you run into any more issues let me know.

Sorry for the delay! I've been busy lately and couldn't get around to fixing this.

**Comment by reeceypie** [comment]
Oh ok. Thanks!
